 const dataInfo = [
  {
    firstName: "Hudson",
    lastName: "Baker",
    admissionId: 3455,
    status: "pending",
    createdAt: "12/11/2023",
  },
  {
    firstName: "Emily",
    lastName: "Johnson",
    admissionId: 6789,
    status: "approved",
    createdAt: "10/15/2023",
  },
  {
    firstName: "James",
    lastName: "Smith",
    admissionId: 1234,
    status: "rejected",
    createdAt: "09/20/2023",
  },
  {
    firstName: "Olivia",
    lastName: "Williams",
    admissionId: 5678,
    status: "pending",
    createdAt: "11/10/2023",
  },
  {
    firstName: "Sophia",
    lastName: "Brown",
    admissionId: 9012,
    status: "approved",
    createdAt: "08/12/2023",
  },
  {
    firstName: "Mia",
    lastName: "Davis",
    admissionId: 3456,
    status: "rejected",
    createdAt: "12/05/2023",
  },
  {
    firstName: "Charles",
    lastName: "Miller",
    admissionId: 7890,
    status: "pending",
    createdAt: "10/25/2023",
  },
  {
    firstName: "Amelia",
    lastName: "Garcia",
    admissionId: 1235,
    status: "approved",
    createdAt: "09/17/2023",
  },
  {
    firstName: "Ethan",
    lastName: "Rodriguez",
    admissionId: 4567,
    status: "rejected",
    createdAt: "11/08/2023",
  },
  {
    firstName: "Jacob",
    lastName: "Wilson",
    admissionId: 8901,
    status: "pending",
    createdAt: "12/20/2023",
  },
  {
    firstName: "Isabella",
    lastName: "Martinez",
    admissionId: 2345,
    status: "approved",
    createdAt: "08/03/2023",
  },
  {
    firstName: "Benjamin",
    lastName: "Anderson",
    admissionId: 6789,
    status: "rejected",
    createdAt: "12/15/2023",
  },
  {
    firstName: "Lucas",
    lastName: "Thomas",
    admissionId: 1234,
    status: "pending",
    createdAt: "09/20/2023",
  },
  {
    firstName: "Mason",
    lastName: "Jackson",
    admissionId: 5678,
    status: "approved",
    createdAt: "11/10/2023",
  },
  {
    firstName: "Emma",
    lastName: "White",
    admissionId: 9012,
    status: "rejected",
    createdAt: "08/12/2023",
  },
  {
    firstName: "Olivia",
    lastName: "Harris",
    admissionId: 3456,
    status: "pending",
    createdAt: "12/05/2023",
  },
  {
    firstName: "Sophia",
    lastName: "Clark",
    admissionId: 7890,
    status: "approved",
    createdAt: "09/17/2023",
  },
  {
    firstName: "Charles",
    lastName: "Lewis",
    admissionId: 4567,
    status: "rejected",
    createdAt: "11/08/2023",
  },
  {
    firstName: "Amelia",
    lastName: "Green",
    admissionId: 8901,
    status: "pending",
    createdAt: "12/20/2023",
  },
  {
    firstName: "Ethan",
    lastName: "Baker",
    admissionId: 2345,
    status: "approved",
    createdAt: "08/03/2023",
  },
  {
    firstName: "Jacob",
    lastName: "Gonzalez",
    admissionId: 6789,
    status: "rejected",
    createdAt: "12/15/2023",
  },
];


export default dataInfo