export const registerFormKeys = {
  organizationTypes: "",
  organizationName: "",
  organizationEmail: "",
  organizationPhoneNumber: "",
  organizationAddress: "",
  organizationEducationLevels: "",
  educationLevel: "",
  churchLevel: "",
  salesAndMarketing: "",
  healthCareLevel: "",
  userRole: "",
  managementSize: "",
  username: "",
  organizationPrivatePublic: "",
  establishmentDate: new Date(),
  userAddress: "",
  phoneNumber: "",
  organizationSize: "",
  organizationDescription: "",
  organizationLogo: "",
  password: "",
  confirmPassword: "",
  email: "",
};

export const StatusIcons = {
  pending: "/assets/Icons/check.svg",
  approved: "/assets/Icons/checked.svg",
  rejected: "/assets/Icons/cancelled.svg",
  // expired: "/assets/Icons/cross.svg",
};
