export const registerFormKeys = {
  organizationTypes: "",
  organizationName: "",
  organizationEmail: "",
  organizationPhoneNumber: "",
  organizationAddress: "",
  organizationEducationLevels: "",
  educationLevel: "",
  churchLevel: "",
  salesAndMarketing: "",
  healthCareLevel: "",
  userRole: "",
  managementSize: "",
  username: "",
  organizationPrivatePublic: "",
  establishmentDate: new Date(),
  userAddress: "",
  phoneNumber: "",
  organizationSize: "",
  organizationDescription: "",
  organizationLogo: "",
  password: "",
};
